<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.1 setup script
 * Date: Sun, 10 Nov 2019 23:25:19 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'gaby1234';

/* End of servers configuration */

$cfg['Console']['Mode'] = 'collapse';
$cfg['blowfish_secret'] = 'UM@h+7B!:H)&e&y@0]M{t[nX&EsUr{gg';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>